@LibraryManagementSystem.API_HostAddress = http://localhost:5126
###

GET http://localhost:5126/patrons
Accept: application/json

###

GET http://localhost:5126/patrons/10537461
Accept: application/json

###

POST http://localhost:5126/patrons
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com"
}

###

PUT http://localhost:5126/patrons/15731951
Content-Type: application/json

{
    "firstName": "Austin",
    "lastName": "Hauger",
    "dateOfBirth": "1996-09-28"
}

###

DELETE http://localhost:5126/patrons/17760022
Accept: application/json

###

GET http://localhost:5126/items
Accept: application/json

###

GET http://localhost:5126/items/10001
Accept: application/json

###